#!/usr/bin/env python3

import json
import os
import shutil
import sys

from os.path import expanduser

HOME_DIR = expanduser('~')
CWD = os.getcwd()

if __name__ == '__main__':
  try:
    with open('package.json', 'r') as f:
      p = json.load(f)
      EXTENSION_NAME = '{}.{}-{}'.format(
        p['publisher'],
        p['name'],
        p['version']
      ).lower()

    # extension dir(s)
    VS_CODE_EXTENSION_DIR = os.path.join(HOME_DIR, '.vscode/extensions/')
    CODIUM_EXTENSION_DIR = os.path.join(HOME_DIR, '.vscode-oss/extensions/')

    # theme dir(s)
    VS_CODE_THEME_DIR = os.path.join(VS_CODE_EXTENSION_DIR, EXTENSION_NAME)
    CODIUM_THEME_DIR = os.path.join(CODIUM_EXTENSION_DIR, EXTENSION_NAME)

    if os.path.exists(VS_CODE_EXTENSION_DIR):
      if os.path.exists(VS_CODE_THEME_DIR):
        print('Deleting Visual Studio Code theme directory: "{}"'.format(VS_CODE_THEME_DIR))
        shutil.rmtree(VS_CODE_THEME_DIR, ignore_errors=True)

      print('Installing theme to "{}"'.format(VS_CODE_THEME_DIR))
      shutil.copytree(CWD, VS_CODE_THEME_DIR)

    if os.path.exists(CODIUM_EXTENSION_DIR):
      if os.path.exists(CODIUM_THEME_DIR):
        print('Deleting Codium theme directory: "{}"'.format(CODIUM_THEME_DIR))
        shutil.rmtree(CODIUM_THEME_DIR, ignore_errors=True)

      print('Installing theme to "{}"'.format(CODIUM_THEME_DIR))
      shutil.copytree(CWD, CODIUM_THEME_DIR)

  except Exception as e:
    print(e)
    sys.exit(1)
